/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.sysbank.view;

import br.edu.sysbank.controller.CtrlEndereco;
import br.edu.sysbank.controller.CtrlFuncionario;
import br.edu.sysbank.model.Cargo;
import br.edu.sysbank.model.Endereco;
import br.edu.sysbank.model.Funcionario;
import com.sun.glass.events.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class IFormFuncionario extends javax.swing.JInternalFrame {
    
    DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
    List<Cargo> cargos = new ArrayList<>();
    CtrlFuncionario ctrlFuncionario;
    Funcionario funcionario;
    
    public IFormFuncionario() {
        initComponents();
        mostraCargos();
    }
    
    public IFormFuncionario(long id){
        initComponents();
        preparaCampos(id);
    }
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelCPF = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelNumero = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabelLogradouro = new javax.swing.JLabel();
        jTextFieldLogradouro = new javax.swing.JTextField();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabelBairro = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldComplemento = new javax.swing.JTextField();
        jLabelComplemento = new javax.swing.JLabel();
        jLabelCEP = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabelUF = new javax.swing.JLabel();
        jTextFieldUF = new javax.swing.JTextField();
        jLabelSenha1 = new javax.swing.JLabel();
        jPasswordFieldSenha1 = new javax.swing.JPasswordField();
        jPasswordFieldSenha2 = new javax.swing.JPasswordField();
        jLabelSenha2 = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCEP = new javax.swing.JFormattedTextField();
        jButtonBuscaCEP = new javax.swing.JButton();
        jComboBoxCargo = new javax.swing.JComboBox<>();
        jLabelCargo = new javax.swing.JLabel();
        jButtonAddCargo = new javax.swing.JButton();

        jLabelCPF.setText("CPF:");

        jLabelNome.setText("Nome:");

        jLabelNumero.setText("Numero:");

        jLabelLogradouro.setText("Logradouro:");

        jLabelBairro.setText("Bairro:");

        jLabelEmail.setText("E-mail:");

        jLabelComplemento.setText("Complemento:");

        jLabelCEP.setText("CEP:");

        jLabelCidade.setText("Cidade:");

        jLabelUF.setText("UF:");

        jLabelSenha1.setText("Senha");

        jLabelSenha2.setText("Confirmar Senha:");

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextFieldCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCEP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldCEPFocusLost(evt);
            }
        });
        jFormattedTextFieldCEP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldCEPKeyPressed(evt);
            }
        });

        jButtonBuscaCEP.setText("Buscar");
        jButtonBuscaCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaCEPActionPerformed(evt);
            }
        });

        jComboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCargoActionPerformed(evt);
            }
        });

        jLabelCargo.setText("Cargo:");

        jButtonAddCargo.setText("Novo Cargo");
        jButtonAddCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCargoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNome)
                                    .addComponent(jLabelEmail)
                                    .addComponent(jLabelCPF)
                                    .addComponent(jLabelNumero))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelCEP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonBuscaCEP))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(28, 28, 28)
                                            .addComponent(jLabelComplemento)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelLogradouro)
                                    .addComponent(jLabelBairro)
                                    .addComponent(jLabelUF)
                                    .addComponent(jLabelSenha1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jPasswordFieldSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabelSenha2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jPasswordFieldSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextFieldLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelCidade)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldUF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabelCargo)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonAddCargo)))))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelar)
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCPF)
                    .addComponent(jLabelCEP)
                    .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscaCEP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelComplemento)
                    .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLogradouro)
                    .addComponent(jTextFieldLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCidade)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBairro)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUF)
                    .addComponent(jComboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCargo)
                    .addComponent(jButtonAddCargo))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSenha1)
                    .addComponent(jPasswordFieldSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSenha2)
                    .addComponent(jPasswordFieldSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        Endereco e = new Endereco();
        
        e.setCEP(jFormattedTextFieldCEP.getText());
        e.setBairro(jTextFieldBairro.getText());
        e.setLogradouro(jTextFieldLogradouro.getText());
        e.setCidade(jTextFieldCidade.getText());
        e.setUF(jTextFieldUF.getText());
        
        funcionario = new Funcionario(e);
        Cargo cargo = new Cargo();

        funcionario.setNome(jTextFieldNome.getText());
        funcionario.setEmail(jTextFieldEmail.getText());
        funcionario.setCpf(jFormattedTextFieldCPF.getText());
        funcionario.setNumero(jTextFieldNumero.getText());
        funcionario.setComplemento(jTextFieldComplemento.getText());
        funcionario.setPws(new String(jPasswordFieldSenha1.getPassword()));
        cargo.setIdCargo(cargos.get(jComboBoxCargo.getSelectedIndex()).getIdCargo());
        cargo.setNomeCargo(cargos.get(jComboBoxCargo.getSelectedIndex()).getNomeCargo());
        funcionario.setCargo(cargo);
        //System.out.println(jPasswordFieldSenha1.getPassword().toString());

        
        ctrlFuncionario = new CtrlFuncionario();
        String erros = "";
        if (this.getTitle().equals("Atualizar Funcionario")) {
            erros = ctrlFuncionario.valida(funcionario);
            if (erros.equals("")) {
                try {
                    if (ctrlFuncionario.atualizar(funcionario)) {
                        JOptionPane.showMessageDialog(null, "Atuallizado", "Aviso", 1);
                        
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Erro ao atualizar no Sistema.", "ERRO", 0);
                }
            } else {
                JOptionPane.showMessageDialog(null, erros, "Erro(s) ao cadastrar", 0);
            }
        } else {
            erros = ctrlFuncionario.valida(funcionario, new String(jPasswordFieldSenha2.getPassword()));
            if (erros.equals("")) {
                if (ctrlFuncionario.salvar(funcionario)) {
                    JOptionPane.showMessageDialog(null, "Cadastrado", "Aviso", 1);
                    limparCampos();
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao Cadastrar no Sistema", "ERRO", 0);
                }
            } else {
                JOptionPane.showMessageDialog(null, erros, "Erro(s) ao cadastrar", 0);
            }
        }
        jButtonCancelar.doClick();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonBuscaCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaCEPActionPerformed
        // TODO add your handling code here:
        CtrlEndereco ctrlEndereco = new CtrlEndereco();
        Endereco endereco = ctrlEndereco.pesquisar(jFormattedTextFieldCEP.getText());
        
        if(endereco == null){
            JOptionPane.showMessageDialog(null, "CEP não localizado.");
        }else{
            jTextFieldBairro.setText(endereco.getBairro());
            jTextFieldCidade.setText(endereco.getCidade());
            jTextFieldLogradouro.setText(endereco.getLogradouro());
            jTextFieldUF.setText(endereco.getUF());
        }
    }//GEN-LAST:event_jButtonBuscaCEPActionPerformed

    private void jFormattedTextFieldCEPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCEPFocusLost
        // TODO add your handling code here:
        jButtonBuscaCEP.doClick();
    }//GEN-LAST:event_jFormattedTextFieldCEPFocusLost

    private void jFormattedTextFieldCEPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCEPKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonBuscaCEP.doClick();
        }
    }//GEN-LAST:event_jFormattedTextFieldCEPKeyPressed

    private void jComboBoxCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCargoActionPerformed

    private void jButtonAddCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCargoActionPerformed
        // TODO add your handling code here:
        //add um metodo add cargos no banco. ********************
        
        String nome = JOptionPane.showInputDialog(null, "Qual o cargo desejado?" ,"Adicionar Cargo");
        if(JOptionPane.showConfirmDialog(null, "Deseja realmente adicionar " + nome + " ao banco de dados?") != 0){
            
        }else{
            if(ctrlFuncionario.adicionarCargo(nome)){
                JOptionPane.showMessageDialog(null, "Cargo cadastrado com sucesso!!!", "Cadastro de cargo", 1);
                mostraCargos();
            }else{
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar cargo!!!", "Cadastro de cargo", 0);
            }
        }
        
    }//GEN-LAST:event_jButtonAddCargoActionPerformed
    
    public void mostraCargos(){
        try{
            ctrlFuncionario = new CtrlFuncionario();
            cargos = ctrlFuncionario.listarCargos();

            modeloCombo.removeAllElements();
            jComboBoxCargo.setModel(modeloCombo);

            if(!cargos.isEmpty()){
                for(Cargo c : cargos){
                    jComboBoxCargo.addItem(c.getNomeCargo());
                    if(this.getTitle().equals("Atualizar Funcionario")){
                        if(c.getNomeCargo().equals(funcionario.getCargo().getNomeCargo())){
                            jComboBoxCargo.setSelectedItem(c.getNomeCargo());
                        }
                    }
                }
            }
        }catch(Exception erro){
            System.err.println("Erro ao pesquisar cargos: " + erro);
        }
    }
    
    public void preparaCampos(long id){
        this.setTitle("Atualizar Funcionario");
        jPasswordFieldSenha1.setVisible(false);
        jPasswordFieldSenha2.setVisible(false);
        jLabelSenha1.setVisible(false);
        jLabelSenha2.setVisible(false);

        jFormattedTextFieldCPF.setEnabled(false);
        jTextFieldLogradouro.setEnabled(false);
        jTextFieldBairro.setEnabled(false);
        jTextFieldCidade.setEnabled(false);
        jTextFieldUF.setEnabled(false);

        ctrlFuncionario = new CtrlFuncionario();
        funcionario = ctrlFuncionario.getFuncionario(id);

        jTextFieldNome.setText(funcionario.getNome());
        jFormattedTextFieldCPF.setText(funcionario.getCpf());
        jTextFieldEmail.setText(funcionario.getEmail());
        jTextFieldNumero.setText(funcionario.getNumero());
        jTextFieldComplemento.setText(funcionario.getComplemento());
        jFormattedTextFieldCEP.setText(funcionario.getEndereco().getCEP());
        jTextFieldLogradouro.setText(funcionario.getEndereco().getLogradouro());
        jTextFieldBairro.setText(funcionario.getEndereco().getBairro());
        jTextFieldCidade.setText(funcionario.getEndereco().getCidade());
        jTextFieldUF.setText(funcionario.getEndereco().getUF());
        mostraCargos();
        
    }
    
    public void limparCampos(){
        jTextFieldNome.setText("");
        jFormattedTextFieldCPF.setText("");
        jTextFieldEmail.setText("");
        jTextFieldNumero.setText("");
        jTextFieldComplemento.setText("");
        jFormattedTextFieldCEP.setText("");
        jTextFieldLogradouro.setText("");
        jTextFieldBairro.setText("");
        jTextFieldCidade.setText("");
        jTextFieldUF.setText("");
        jPasswordFieldSenha1.setText("");
        jPasswordFieldSenha2.setText("");
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAddCargo;
    private javax.swing.JButton jButtonBuscaCEP;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxCargo;
    private javax.swing.JFormattedTextField jFormattedTextFieldCEP;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCEP;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCargo;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelComplemento;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelLogradouro;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelSenha1;
    private javax.swing.JLabel jLabelSenha2;
    private javax.swing.JLabel jLabelUF;
    private javax.swing.JPasswordField jPasswordFieldSenha1;
    private javax.swing.JPasswordField jPasswordFieldSenha2;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldLogradouro;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldUF;
    // End of variables declaration//GEN-END:variables
}
